[package]
name = "hangman"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
serde ={ version = "1.0,
features =["derive]}
serde_json = "1.0"
colored = "2.0"
text_io = "0.1"
rpassword = "5.0"
reqwest = "0.11"
